-- Create profiles table for user management
-- Run this in Supabase SQL editor

create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  display_name text,
  role text check (role in ('student', 'faculty', 'admin')) default 'student',
  onboarded boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.profiles enable row level security;

-- Create policies
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using (true);

create policy "Users can insert their own profile."
  on profiles for insert
  with check (auth.uid() = id);

create policy "Users can update own profile."
  on profiles for update
  using (auth.uid() = id);

-- Create trigger to create profile on user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, display_name, role)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data->>'full_name',
      new.raw_user_meta_data->>'name',
      split_part(new.email, '@', 1)
    ),
    'student'
  );
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create audit_logs table for admin actions
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null,
  actor text not null,
  action text not null,
  details text
);

-- Enable RLS for audit_logs
alter table public.audit_logs enable row level security;

-- Only admins can view audit logs
create policy "Only admins can view audit logs"
  on audit_logs for select
  using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- Only admins can insert audit logs
create policy "Only admins can insert audit logs"
  on audit_logs for insert
  with check (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );